version: "3.8"
services:
  app:
    build: .
    container_name: laravel_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      APP_ENV: production
      APP_KEY: YOUR_APP_KEY_HERE
      DATABASE_URL: YOUR_DATABASE_URL_HERE
    networks:
      - laravel

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:

volumes:
  pgdata:
